export default {
    puff: false,
    story: [""],
    // story: "",
    // storyTag: [],
    // question: "What is the most likely diagnosis in this case?",
    // question: "",
    storyCatFields: [],
    apiData: [],
    tempCat: [],
    storyIndex: [],
    storyCategoriesFields: [],
    topic: '',
    question: [],
    MCQs: [],
    questionSubmitForm: [],
    questionformchip: {},
    correctOptions: {},
    correctMultipleOptions: {},
    questionCategoryValue: [],
    // questionTagValueChange:[],
    possibleCases: '',
    questionTagsValue: [],
    selectedFeatures: [],
    // answers: ["option 1", "option 2", "option 3", "option 4", "option 5"],
    answers: {},
    data: [],
    answersData: [],
    // fields: { age: [5, 6, 7, 8], gender: ["male", "female"] },
    fields: {},
    tagfields: {},
    chiptagbtn: false,
    // categoriesFields: {},
    categoriesFields: [],
    categoriesInputVisible: true,
    // categoriesInputValue: ["male", "female"],
    inputVisible: {},
    inputValue: {},
    imported: false,
    isGenerated: false,
    // correctAnswer: "Aspiration pneumonitis",
    // questions: [
    //   {
    //     tagName: "firstTag",
    //     options: [
    //       {
    //         chipName: "age",
    //         options: ["jj", "kk", "ll"],
    //         selected: "jj",
    //       },
    //       {
    //         chipName: "color",
    //         options: ["jj", "kk", "ll"],
    //         selected: "ll",
    //       },
    //     ],
    //   },
    //   {
    //     tagName: "firstTag",
    //     options: [
    //       {
    //         chipName: "age",
    //         options: ["jj", "kk", "ll"],
    //         selected: "jj",
    //       },
    //       {
    //         chipName: "color",
    //         options: ["jj", "kk", "ll"],
    //         selected: "ll",
    //       },
    //     ],
    //   },
    // ],
    genderSelect: [],
    MCQsItems: [],
}